#exp name and save dir
exp_name: 'semi_crnn_uni_universal_fgsm_pas_swish'
checkpoint_dir: 'exp/'

#Data
resume: ''
data_file: 'data_semi'
universal: False
language_one_hot: False
semi: False
mme_lambda: 0
dat_lambda: 0
left_ctx: 0
right_ctx: 2
n_skip_frame: 2
n_downsample: 2
num_workers: 1
shuffle_train: True
feature_dim: 40
# This one is important!
# output_class_dim: 52
mel: False
feature_type: "fbank"

#Model
rnn_input_size: 120
rnn_hidden_size: 384
rnn_layers: 4
rnn_type: "nn.LSTM"
bidirectional: False
batch_norm: True
drop_out: 0.2

#CNN
add_cnn: True
layers: 2
channel: "[(1, 32), (32, 32)]"
kernel_size: "[(3, 3), (3, 3)]"
stride: "[(1, 2), (2, 2)]"
padding: "[(1, 1), (1, 1)]"
pooling: "None"
batch_norm: True
activation_function: "swish"

#[Training]
use_gpu: True
init_lr: 0.001
num_epoches: 80
end_adjust_acc: 2
lr_decay: 0.5
batch_size: 8
weight_decay: 0.0005
seed: 1
verbose_step: 50

#[test]
test_dir: 'data_semi'
decode_type: "soft"
separator: "<eow>"
beam_width: 10
# lm_alpha: 0.1
# lm_path: 'data_multi/Italian/lm_phone_bg.arpa'

at_config: "conf/at.yaml"
